.PHONY: all preprocess add_factors strategy_signals backtest_performance clean

all: add_factors strategy_signals backtest_performance

add_factors:
	python3.12 add_factors.py

strategy_signals:
	python3.12 strategy_signals.py

backtest_performance:
	python3.12 backtest_performance.py

clean:
	@echo "No clean steps defined."
